version: '3'
services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: post
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    container_name: post_app
    image: 'post_office'
    build:
      context: src/main/java/ru/skyeng
    ports:
      - "8090:8090"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/post
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres






